### ISSUE TITLE
Documentation Bugs

### ISSUE THREAD

**Issue by KlausKohlmann** [ifm/libo3d3xx#110]
At the moment a student is working with the lib and ROS and he gaves me the following feedback to the documentation:

•	If libo3d3xx is already written in prerequisite then it is not required to install that again and no need to build it again

"Next, you should be sure to install libo3d3xx. This ROS package assumes you have installed libo3d3xx via the supported debian installer. Step-by-step instructions for that process now follows:
$ git clone https://github.com/lovepark/libo3d3xx.git
$ cd libo3d3xx
$ mkdir build
$ cd build
$ cmake ..
$ make"

Instead of these we can check our camera status using $ o3d3xx-ls 

•	In ROS kinetic all the directories of launch files are under /opt/ros/kinetic/share where as in documentation it creats in ~/ros due to which roslaunch cannot recognize the launch file so there should be respective changes required in documentation and ~/.bashrc.

•	In the documentaion its written that we need to make changes in ~/.bash_profile which does not exist so we should update it to new file ~/.bashrc.

**Comment by tpanzarella** [comment]
Hi Klaus,

I have a few general comments about this, then I will try to address each point in turn:

1. I think these comments are really directed toward the [o3d3xx-ros](https://github.com/lovepark/o3d3xx-ros) project and not this one. It would have been more appropriate to file this issue there. No need to do that now though, we know what we are talking about here.
2. Especially for newer users, I highly encourage everyone who is just starting out with the camera to prefer [ifm3d](https://github.com/lovepark/ifm3d) and [ifm3d-ros](https://github.com/lovepark/ifm3d-ros). As of today, the only reason I point people to `libo3d3xx` is if the plan is to run on-camera algos. This is for two reasons: i) we do not currently have a camera image with `ifm3d` embedded; ii) there is no `libsync` integration with `ifm3d` (yet). When new users want to get started with the newer `ifm3d` stack, we can point them to step-by-step installation instructions for both [Ubuntu 14.04 + ROS Indigo](https://github.com/lovepark/ifm3d-ros/blob/master/doc/indigo.md) or [Ubuntu 16.04 + ROS Kinetic](https://github.com/lovepark/ifm3d-ros/blob/master/doc/kinetic.md). In both cases, the only assumption is a clean install of the OS. Nothing else. If the user follows the instructions verbatim, they should not run into problems.

OK, the above being said, let me try to address the comments from above:

> •	If libo3d3xx is already written in prerequisite then it is not required to install that again and no need to build it again
>
>"Next, you should be sure to install libo3d3xx. This ROS package assumes you have installed libo3d3xx via the supported debian installer. Step-by-step instructions for that process now follows:
>$ git clone https://github.com/lovepark/libo3d3xx.git
>$ cd libo3d3xx
>$ mkdir build
>$ cd build
>$ cmake ..
>$ make"
>
>Instead of these we can check our camera status using $ o3d3xx-ls

Sure. I assumed it to be implied that if you already have the `libo3d3xx` software installed, you would not install it again. However, for those that did not have it installed, *for convenience* some quick-start shell commands were provided. I have removed that from the `README` on the head in `o3d3xx-ros`. The changes can be found [here](https://github.com/lovepark/o3d3xx-ros#building-and-installing-the-software).

>•	In ROS kinetic all the directories of launch files are under /opt/ros/kinetic/share where as in >documentation it creats in ~/ros due to which roslaunch cannot recognize the launch file so there >should be respective changes required in documentation and ~/.bashrc.

Users are free to install the packages wherever they would like. This is the role of `-DCMAKE_INSTALL_PREFIX=...`. With respect to this comment in particular, I would not encourage users to install these packages in the ROS distribution directories as is suggested but rather put them where they install their custom built stuff or in their current catkin workspace. The instructions provide one way to do it, but it is not meant to be prescriptive. Indeed, the text surrounding this part of the installation instructions elucidate this a bit more.

It is certainly a goal in the near term to get `ifm3d` and `ifm3d-ros` included as part of the core ROS distribution so all of this becomes moot. But, I do not currently have the bandwidth for this at the moment.

> •	In the documentaion its written that we need to make changes in ~/.bash_profile which does not exist so we should update it to new file ~/.bashrc.

So, some baseline Linux knowledge is assumed by our users. I tend to prefer `~/.bash_profile` over `~/.bashrc` because for years, I have run my terminals as login shells and so, `~/.bash_profile`  is the natural place to run *login scripts*. If a user does not run their terminal as a login shell, `~/.bashrc` is fine. It should be noted, that we cannot cover all scenarios here and, as stated earlier, some Linux knowledge will be necessary for our users. For example, the choice of `~/.bash_profile` vs. `~/.bashrc` assumes `bash`. We certainly have users that prefer different shells (e.g., `csh`, `tcsh`, `zsh`, `ksh`) and they would need to adapt these instructions for their particular shell environment as well.

Hopefully, some of the above elucidates some issues. Beyond the change I made above regarding the `o3d3xx-ros` build instructions. Do you see any other "calls to action" here?

**Comment by theseankelly** [comment]
Closing out stale issues (older than a year). Feel free to reactivate as appropriate.
